[workspace]
channels = ["conda-forge"]
name = "cppyy"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "6.30.0"

[environments]
feedstock-dev = ["feedstock-dev"]

cppyy-cling-dev-builtin-llvm = ["cppyy-cling-dev", "cppyy-cling-dev-builtin-llvm", "builtin-llvm"]
cppyy-cling-dev-conda-forge-llvm = ["cppyy-cling-dev", "cppyy-cling-dev-conda-forge-llvm", "conda-forge-llvm"]

# TODO: Make these environments available, see README.md
# cppyy-backend-dev-local-builtin-llvm = [?]
# cppyy-backend-dev-local-conda-forge-llvm = [?]
cppyy-backend-dev-conda-forge = ["cppyy-backend-dev", "cppyy-backend-dev-conda-forge", "cppyy-cling-conda-forge"]
cppyy-backend-dev-pypi = ["cppyy-backend-dev", "cppyy-backend-dev-pypi", "cppyy-cling-pypi"]

# TODO: Make these environments available, see README.md
# cpycppyy-dev-local-builtin-llvm = [?]
# cpycppyy-dev-local-conda-forge-llvm = [?]
cpycppyy-dev-conda-forge = ["cpycppyy-dev", "cpycppyy-dev-conda-forge", "cppyy-cling-conda-forge", "cppyy-backend-conda-forge"]
cpycppyy-dev-pypi = ["cpycppyy-dev", "cpycppyy-dev-pypi", "cppyy-cling-pypi", "cppyy-backend-pypi"]

# TODO: Make these environments available, see README.md
# cppyy-dev-local-builtin-llvm = [?]
# cppyy-dev-local-conda-forge-llvm = [?]
cppyy-dev-conda-forge = ["cppyy-dev", "cppyy-dev-conda-forge", "cppyy-cling-conda-forge", "cppyy-backend-conda-forge", "cpycppyy-conda-forge"]
cppyy-dev-pypi = ["cppyy-dev", "cppyy-dev-pypi", "cppyy-cling-pypi", "cppyy-backend-pypi", "cpycppyy-pypi"]

cppyy-pypi = ["cppyy-dev", "cppyy-pypi"]
cppyy-conda-forge = ["cppyy-dev", "cppyy-conda-forge"]

################
# DEPENDENCIES #
################
[dependencies]
ccache = "*"
cxx-compiler = "*"
jq = "*"
mamba = "*"
pip = "*"
setuptools = "*"

[feature.feedstock-dev.dependencies]
conda-build = "*"
conda-smithy = "*"
conda-recipe-manager = "*"

[feature.cppyy-cling-dev.dependencies]
cmake = "*"
findutils = "*"
libboost-headers = "*"
libxml2 = "*"
make = "*"
pip = "*"
python = "*"
sed = "*"
setuptools = "*"
zlib = "*"

[feature.builtin-llvm.target.osx.dependencies]
# cppyy-cling vendors clang 13. However, recent versions of libcxx do not support such an old clang and fail with "Libc++ only supports Clang 17 and later".
libcxx = "<19"

[feature.conda-forge-llvm.dependencies]
clangdev = { version="13.*", build="root_63004*" }

[feature.cppyy-cling-conda-forge.dependencies]
cppyy-cling = "==6.30.0"

[feature.cppyy-backend-conda-forge.dependencies]
cppyy-backend = "==1.15.2"

[feature.cpycppyy-conda-forge.dependencies]
cpycppyy = "==1.12.16"

[feature.cppyy-conda-forge.dependencies]
cppyy = "==3.1.2"

[feature.cppyy-cling-pypi.pypi-dependencies]
cppyy-cling = "==6.30.0"

[feature.cppyy-backend-pypi.pypi-dependencies]
cppyy-backend = "==1.15.2"

[feature.cpycppyy-pypi.pypi-dependencies]
cpycppyy = "==1.12.16"

[feature.cppyy-pypi.pypi-dependencies]
cppyy = "==3.1.2"

[feature.cppyy-dev.dependencies]
# We install a version of Python that is compatible with the current builds of SageMath for downstream/ testing
python = "<3.13"
make = "*"
pytest = "*"
pytest-xdist = "*"

[feature.cppyy-dev.pypi-dependencies]
pytest-isolate = "*"
pytest-timeout = "*"

[feature.cppyy-pypi.target.linux.dependencies]
# Clang 13 which cppyy 3.1.2 is based upon cannot parse GCC 12 headers, see https://github.com/wlav/cppyy/issues/285
gcc = "<12"

#########
# TASKS #
#########
[feature.cppyy-cling-dev.tasks.create-src-directory]
cmd = "./create_src_directory.py"
cwd = "upstream/cppyy-backend/cling"

[feature.cppyy-cling-dev.tasks.configure-cppyy-cling-patched-builtin-llvm]
cmd = "mkdir -p build && cd build && cmake ../src $CMAKE_ARGS $CMAKE_ARGS_CPPYY_CLING -Dbuiltin_llvm=ON -Dbuiltin_clang=ON"
cwd = "patched/cppyy-cling"

[feature.cppyy-cling-dev.tasks.configure-cppyy-cling-patched-conda-forge-llvm]
cmd = "mkdir -p build && cd build && cmake ../src $CMAKE_ARGS $CMAKE_ARGS_CPPYY_CLING -Dbuiltin_llvm=OFF -Dbuiltin_clang=OFF"
cwd = "patched/cppyy-cling"

[feature.cppyy-cling-dev.tasks.configure-cppyy-cling-upstream-builtin-llvm]
cmd = "mkdir -p builddir && cd builddir && cmake ../src $CMAKE_ARGS $CMAKE_ARGS_CPPYY_CLING -Dbuiltin_llvm=ON -Dbuiltin_clang=ON"
cwd = "upstream/cppyy-backend/cling"

[feature.cppyy-cling-dev.tasks.configure-cppyy-cling-upstream-conda-forge-llvm]
cmd = "mkdir -p builddir && cd builddir && cmake ../src $CMAKE_ARGS $CMAKE_ARGS_CPPYY_CLING -Dbuiltin_llvm=OFF -Dbuiltin_clang=OFF"
cwd = "upstream/cppyy-backend/cling"

[feature.cppyy-cling-dev.tasks.build-cppyy-cling-patched]
cmd = "make"
cwd = "patched/cppyy-cling/build"

[feature.cppyy-cling-dev.tasks.build-cppyy-cling-upstream]
cmd = "make"
cwd = "upstream/cppyy-backend/cling/builddir"

[feature.cppyy-cling-dev.tasks.install-cppyy-cling-patched]
cmd = "python setup.py install --skip-build"
cwd = "patched/cppyy-cling"

[feature.cppyy-cling-dev.tasks.install-cppyy-cling-upstream]
cmd = "python setup.py install --skip-build"
cwd = "upstream/cppyy-backend/cling"

[feature.cppyy-cling-dev-builtin-llvm.tasks.install-cppyy-cling-from-patched]
depends-on = ["configure-cppyy-cling-patched-builtin-llvm", "build-cppyy-cling-patched", "install-cppyy-cling-patched"]

[feature.cppyy-cling-dev-conda-forge-llvm.tasks.install-cppyy-cling-from-patched]
depends-on = ["configure-cppyy-cling-patched-conda-forge-llvm", "build-cppyy-cling-patched", "install-cppyy-cling-patched"]

[feature.cppyy-cling-dev-builtin-llvm.tasks.install-cppyy-cling-from-upstream]
depends-on = ["create-src-directory", "configure-cppyy-cling-upstream-builtin-llvm", "build-cppyy-cling-upstream", "install-cppyy-cling-upstream"]

[feature.cppyy-cling-dev-conda-forge-llvm.tasks.install-cppyy-cling-from-upstream]
depends-on = ["create-src-directory", "configure-cppyy-cling-upstream-conda-forge-llvm", "build-cppyy-cling-upstream", "install-cppyy-cling-upstream"]

[feature.cppyy-cling-dev-builtin-llvm.tasks.install]
depends-on = ["install-cppyy-cling-from-patched"]

[feature.cppyy-cling-dev-conda-forge-llvm.tasks.install]
depends-on = ["install-cppyy-cling-from-patched"]

[feature.cppyy-backend-dev.tasks.install-cppyy-backend-from-pypi]
cmd = "pip install --no-deps --no-build-isolation -v --force-reinstall cppyy-backend==1.15.2"

[feature.cppyy-backend-dev.tasks.install-cppyy-backend-from-patched]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "patched/cppyy-backend"

[feature.cppyy-backend-dev.tasks.install-cppyy-backend-from-upstream]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "upstream/cppyy-backend/clingwrapper"

[feature.cppyy-backend-dev-conda-forge.tasks.install]
depends-on = ["install-cppyy-backend-from-patched"]

[feature.cppyy-backend-dev-pypi.tasks.install]
depends-on = ["install-cppyy-backend-from-patched"]

[feature.cpycppyy-dev.tasks.install-cpycppyy-from-pypi]
cmd = "pip install --no-deps --no-build-isolation -v --force-reinstall cpycppyy==1.12.16"

[feature.cpycppyy-dev.tasks.install-cpycppyy-from-patched]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "patched/cpycppyy"

[feature.cpycppyy-dev.tasks.install-cpycppyy-from-upstream]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "upstream/CPyCppyy"

[feature.cpycppyy-dev-conda-forge.tasks.install]
depends-on = ["install-cpycppyy-from-patched"]

[feature.cpycppyy-dev-pypi.tasks.install]
depends-on = ["install-cpycppyy-from-patched"]

[feature.cppyy-dev.tasks.test]
# TODO: Tests do not pass:
# In cppyy-pypi, 36 failed, quite a few segfaults.
# In cppyy-conda-forge, 31 failed, quite a few segfaults.
# In CI, tests sometimes hang, so we set a timeout to terminate them anyway.
cmd = "make && EXTRA_CLING_ARGS=-I$(pwd)/../../CPyCppyy/include pytest --isolate --timeout=60 -n$(nproc || sysctl -n hw.ncpu)"
cwd = "upstream/cppyy/test"

[feature.cppyy-dev.tasks.install-cppyy-from-pypi]
cmd = "pip install --no-deps --no-build-isolation -v --force-reinstall cppyy==3.1.2"

[feature.cppyy-dev.tasks.install-cppyy-from-patched]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "patched/cppyy"

[feature.cppyy-dev.tasks.install-cppyy-from-upstream]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "upstream/cppyy"

[feature.cppyy-dev.tasks.install-flatsurf-suite]
depends-on = ["install-flatsurf-suite-dependencies", "install-gmpxxyy", "install-cppyythonizations", "install-e-antic", "install-exact-real", "install-intervalxt", "install-flatsurf", "install-sage-flatsurf"]

[feature.cppyy-dev.tasks.install-flatsurf-suite-dependencies]
# TODO: Teach intervalxt to handle fmt=12.
cmd = "mamba install autoconf automake libtool make sagelib ipywidgets boost-cpp ruamel.yaml benchmark hatchling surface-dynamics fmt=11.'*' gmpxxll more-itertools matplotlib-base && pip install realalg bidict"

[feature.cppyy-dev.tasks.test-cppyythonizations]
cmd = "pytest --isolate --doctest-modules -n$(nproc || sysctl -n hw.ncpu)"
cwd = "downstream/cppyythonizations"

[feature.cppyy-dev.tasks.install-cppyythonizations]
cmd = "pip install ."
cwd = "downstream/cppyythonizations"

[feature.cppyy-dev.tasks.build-gmpxxyy]
cmd = "./bootstrap && ./configure --prefix=$CONDA_PREFIX && make"
cwd = "downstream/gmpxxyy"

[feature.cppyy-dev.tasks.install-gmpxxyy]
depends-on = ["build-gmpxxyy"]
cmd = "make install"
cwd = "downstream/gmpxxyy"

[feature.cppyy-dev.tasks.test-gmpxxyy]
depends-on = ["build-gmpxxyy"]
cmd = "make check"
cwd = "downstream/gmpxxyy"

[feature.cppyy-dev.tasks.build-e-antic]
cmd = "./bootstrap && ./configure --without-doc --prefix=$CONDA_PREFIX CC=ccache' '$CC CXX=ccache' '$CXX && make"
cwd = "downstream/e-antic"

[feature.cppyy-dev.tasks.install-e-antic]
depends-on = ["build-e-antic"]
cmd = "make install"
cwd = "downstream/e-antic"

[feature.cppyy-dev.tasks.test-e-antic]
depends-on = ["build-e-antic"]
cmd = "make check"
cwd = "downstream/e-antic"

[feature.cppyy-dev.tasks.build-exact-real]
cmd = "./bootstrap && ./configure --without-doc --prefix=$CONDA_PREFIX CC=ccache' '$CC CXX=ccache' '$CXX && make"
cwd = "downstream/exact-real"

[feature.cppyy-dev.tasks.install-exact-real]
depends-on = ["build-exact-real"]
cmd = "make install"
cwd = "downstream/exact-real"

[feature.cppyy-dev.tasks.test-exact-real]
depends-on = ["build-exact-real"]
cmd = "make check"
cwd = "downstream/exact-real"

[feature.cppyy-dev.tasks.build-intervalxt]
cmd = "./bootstrap && ./configure --without-doc --prefix=$CONDA_PREFIX CC=ccache' '$CC CXX=ccache' '$CXX && make"
cwd = "downstream/intervalxt"

[feature.cppyy-dev.tasks.install-intervalxt]
depends-on = ["build-intervalxt"]
cmd = "make install"
cwd = "downstream/intervalxt"

[feature.cppyy-dev.tasks.test-intervalxt]
depends-on = ["build-intervalxt"]
cmd = "make check"
cwd = "downstream/intervalxt"

[feature.cppyy-dev.tasks.build-flatsurf]
cmd = "./bootstrap && ./configure --without-doc --prefix=$CONDA_PREFIX CC=ccache' '$CC CXX=ccache' '$CXX && make"
cwd = "downstream/flatsurf"

[feature.cppyy-dev.tasks.install-flatsurf]
depends-on = ["build-flatsurf"]
cmd = "make install"
cwd = "downstream/flatsurf"

[feature.cppyy-dev.tasks.test-flatsurf]
depends-on = ["build-flatsurf"]
cmd = "make check"
cwd = "downstream/flatsurf"

[feature.cppyy-dev.tasks.install-sage-flatsurf]
cmd = "pip install --no-deps --no-build-isolation -e ."
cwd = "downstream/sage-flatsurf"

[feature.cppyy-dev.tasks.test-sage-flatsurf]
depends-on = ["install-sage-flatsurf"]
cmd = "sage -tp flatsurf"
cwd = "downstream/sage-flatsurf"

[feature.cppyy-dev-conda-forge.tasks.install]
depends-on = ["install-cppyy-from-patched"]

[feature.cppyy-dev-pypi.tasks.install]
depends-on = ["install-cppyy-from-patched"]

##############
# ACTIVATION #
##############
[activation.env]
MAKEFLAGS = "-j$(nproc || sysctl -n hw.ncpu)"
CMAKE_C_COMPILER_LAUNCHER = "ccache"
CMAKE_CXX_COMPILER_LAUNCHER = "ccache"
CMAKE_ARGS = "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX"
# builtin_cling: We want to build cling. That's why we're here.
# runtime_cxxmodules: (whatever that might be) leads to "error: unknown argument: '-fmodule-name'" during the build; also disabled by upstream's setup.py
# CMAKE_CXX_STANDARD: clang at least is using some C++17 features
CMAKE_ARGS_CPPYY_CLING = "-Dbuiltin_cling=ON -Druntime_cxxmodules=OFF -DCMAKE_CXX_STANDARD=17"

[feature.cppyy-cling-dev.activation.env]
# enum-constexpr-conversion: to ignore this compile error on modern compilers: integer value 536870912 is outside the valid range of values [0, 63] for the enumeration type 'EProperty'
CXXFLAGS = "$CXXFLAGS -Wno-enum-constexpr-conversion"
