[workspace]
channels = ["conda-forge"]
name = "cppyy"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "6.30.0"

[environments]
feedstock-dev = ["feedstock-dev"]

cppyy-cling-dev-builtin-llvm = ["cppyy-cling-dev-builtin-llvm", "cppyy-cling-dev", "builtin-llvm"]
cppyy-cling-dev-conda-forge-llvm = ["cppyy-cling-dev-conda-forge-llvm", "cppyy-cling-dev", "conda-forge-llvm"]

cppyy-backend-dev-conda-forge = ["cppyy-backend-dev-conda-forge", "cppyy-backend-dev", "cppyy-cling-conda-forge"]
cppyy-backend-dev-pypi = ["cppyy-backend-dev-pypi", "cppyy-backend-dev", "cppyy-cling-pypi"]

cpycppyy-dev-conda-forge = ["cpycppyy-dev-conda-forge", "cpycppyy-dev", "cppyy-cling-conda-forge", "cppyy-backend-conda-forge"]
cpycppyy-dev-pypi = ["cpycppyy-dev-pypi", "cpycppyy-dev", "cppyy-cling-pypi", "cppyy-backend-pypi"]

cppyy-dev-conda-forge = ["cppyy-dev-conda-forge", "cppyy-dev", "cppyy-cling-conda-forge", "cppyy-backend-conda-forge", "cpycppyy-conda-forge"]
cppyy-dev-pypi = ["cppyy-dev-pypi", "cppyy-dev", "cppyy-cling-pypi", "cppyy-backend-pypi", "cpycppyy-pypi"]

dev-builtin-llvm = ["dev-builtin-llvm", "cppyy-cling-dev", "builtin-llvm", "cppyy-backend-dev", "cpycppyy-dev", "cppyy-dev"]
dev-conda-forge-llvm = ["dev-conda-forge-llvm", "cppyy-cling-dev", "conda-forge-llvm", "cppyy-backend-dev", "cpycppyy-dev", "cppyy-dev"]

cppyy-pypi = ["cppyy-pypi", "cppyy-dev"]
cppyy-conda-forge = ["cppyy-conda-forge", "cppyy-dev"]

################
# DEPENDENCIES #
################
[dependencies]
ccache = "*"
cxx-compiler = "*"
jq = "*"
mamba = ">=2.3"
pip = "*"
# Use a version of setuptools that installs CPyCppyy headers into CPyCppyy/ and not into cpycppyy/, i.e., work around https://github.com/wlav/cppyy/issues/292.
# This does not fix installing something as a pypi-dependencies here since pixi uses a more modern setuptools.
setuptools = "<76"

[feature.feedstock-dev.dependencies]
conda-build = "*"
conda-smithy = "*"
conda-recipe-manager = "*"

[feature.cppyy-cling-dev.dependencies]
cmake = "*"
findutils = "*"
libboost-headers = "*"
libxml2 = "*"
make = "*"
pip = "*"
python = "*"
sed = "*"
zlib = "*"

[feature.builtin-llvm.dependencies]

[feature.conda-forge-llvm.dependencies]
# Upstream uses 6.32.8. However we have no root build for that LLVM so we use the next best.
clangdev = { version="16.*", build="root_632*" }

[feature.cppyy-cling-conda-forge.dependencies]
# TODO: Uncomment once the build is available from conda-forge
# cppyy-cling = "==6.32.8"

[feature.cppyy-backend-conda-forge.dependencies]
# TODO: Uncomment once the build is available from conda-forge
# cppyy-backend = "==1.15.3"

[feature.cpycppyy-conda-forge.dependencies]
# TODO: Uncomment once the build is available from conda-forge
# cpycppyy = "==1.13.0"

[feature.cppyy-conda-forge.dependencies]
# TODO: Uncomment once the build is available from conda-forge
# cppyy = "==3.5.0"

[feature.cppyy-cling-pypi.pypi-dependencies]
cppyy-cling = "==6.32.8"

[feature.cppyy-backend-pypi.pypi-dependencies]
cppyy-backend = "==1.15.3"

[feature.cpycppyy-pypi.pypi-dependencies]
cpycppyy = "==1.13.0"

[feature.cppyy-pypi.pypi-dependencies]
cppyy = "==3.5.0"

[feature.cppyy-dev.dependencies]
libxml2 = "*"
make = "*"
# We install a version of Python that is compatible with the current builds of SageMath for downstream/ testing
python = "<3.13"
pytest = "*"
pytest-xdist = "*"

[feature.cppyy-dev.pypi-dependencies]
pytest-isolate = "*"

#########
# TASKS #
#########
[tasks.clean]
cmd = "git clean -fdx; git submodule foreach --recursive git clean -fdx"

[tasks.reset]
cmd = "git reset --hard && git submodule foreach --recursive git reset --hard && git submodule update --init"

[target.osx.tasks.install-osx-sdk]
args = [
    { "arg" = "version" }
]
cmd = "scripts/install-macos-sdk.sh {{ version }}"

[feature.cppyy-cling-dev.tasks.create-src-directory]
cmd = "./create_src_directory.py"
cwd = "upstream/cppyy-backend/cling"

[feature.cppyy-cling-dev.tasks.configure-cppyy-cling-patched-builtin-llvm]
cmd = "mkdir -p builddir && cd builddir && cmake ../src -DCMAKE_INSTALL_PREFIX=`pwd`/install/cppyy_backend $CMAKE_ARGS_CPPYY_CLING -Dbuiltin_llvm=ON -Dbuiltin_clang=ON"
cwd = "patched/cppyy-cling"

[feature.cppyy-cling-dev.tasks.configure-cppyy-cling-patched-conda-forge-llvm]
# We must set LLVM_CONFIG since otherwise Cling prefers llvm-config-$MAJOR which might be present on the CI system.
cmd = "mkdir -p builddir && cd builddir && cmake ../src -DCMAKE_INSTALL_PREFIX=`pwd`/install/cppyy_backend $CMAKE_ARGS_CPPYY_CLING -Dbuiltin_llvm=OFF -Dbuiltin_clang=OFF -DLLVM_CONFIG=`which llvm-config`"
cwd = "patched/cppyy-cling"

[feature.cppyy-cling-dev.tasks.build-cppyy-cling-patched]
cmd = "make"
cwd = "patched/cppyy-cling/builddir"

[feature.cppyy-cling-dev.tasks.install-cppyy-cling-patched]
cmd = "python setup.py install"
cwd = "patched/cppyy-cling"

[feature.cppyy-cling-dev.tasks.install-cppyy-cling-upstream]
cmd = "python setup.py install"
cwd = "upstream/cppyy-backend/cling"

[feature.cppyy-cling-dev.target.linux.tasks.install-cppyy-cling-upstream]
# We need to disable C++20 features since the builtin clang cannot handle the GCC C++ headers yet, see https://github.com/llvm/llvm-project/issues/52696#issuecomment-1010369642
cmd = "STDCXX=17 python setup.py install"
cwd = "upstream/cppyy-backend/cling"

[feature.cppyy-cling-dev-builtin-llvm.tasks.install-cppyy-cling-from-patched]
depends-on = ["configure-cppyy-cling-patched-builtin-llvm", "build-cppyy-cling-patched", "install-cppyy-cling-patched"]

[feature.cppyy-cling-dev-conda-forge-llvm.tasks.install-cppyy-cling-from-patched]
depends-on = ["configure-cppyy-cling-patched-conda-forge-llvm", "build-cppyy-cling-patched", "install-cppyy-cling-patched"]

[feature.cppyy-cling-dev-builtin-llvm.tasks.install-cppyy-cling-from-upstream]
depends-on = ["create-src-directory", "install-cppyy-cling-upstream"]

[feature.cppyy-cling-dev-builtin-llvm.tasks.install]
depends-on = ["install-cppyy-cling-from-patched"]

[feature.cppyy-cling-dev-conda-forge-llvm.tasks.install]
depends-on = ["install-cppyy-cling-from-patched"]

[feature.cppyy-backend-dev.tasks.install-cppyy-backend-from-pypi]
cmd = "pip install --no-deps --no-build-isolation -v --force-reinstall cppyy-backend==1.15.2"

[feature.cppyy-backend-dev.tasks.install-cppyy-backend-from-patched]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "patched/cppyy-backend"

[feature.cppyy-backend-dev.tasks.install-cppyy-backend-from-upstream]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "upstream/cppyy-backend/clingwrapper"

[feature.cppyy-backend-dev-conda-forge.tasks.install]
depends-on = ["install-cppyy-backend-from-patched"]

[feature.cppyy-backend-dev-pypi.tasks.install]
depends-on = ["install-cppyy-backend-from-patched"]

[feature.cpycppyy-dev.tasks.install-cpycppyy-from-pypi]
cmd = "pip install --no-deps --no-build-isolation -v --force-reinstall cpycppyy==1.12.16"

[feature.cpycppyy-dev.tasks.install-cpycppyy-from-patched]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "patched/cpycppyy"

[feature.cpycppyy-dev.tasks.install-cpycppyy-from-upstream]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "upstream/CPyCppyy"

[feature.cpycppyy-dev-conda-forge.tasks.install]
depends-on = ["install-cpycppyy-from-patched"]

[feature.cpycppyy-dev-pypi.tasks.install]
depends-on = ["install-cpycppyy-from-patched"]

[tasks._precompiled-headers]
# Make sure that cppyy's precompiled headers have been regenerated. This is important when running cppyy in parallel in several processes, e.g., during parallel testing.
# cppyy doesn't crash immediately when multiple processes try to regenerate the headers but some features do not seem to work properly in that case.
cmd = "python -c 'import cppyy'"

[feature.cppyy-dev.tasks.test]
depends-on = ["_precompiled-headers"]
# Tests do not pass, we should check with upstream what we're doing wrong, see https://github.com/wlav/cppyy/issues/325
# In cppyy-pypi, 26 failed, quite a few segfaults.
# In cppyy-conda-forge, 26 failed, quite a few segfaults.
# In CI, tests sometimes hang, so we set a timeout to terminate them anyway.
cmd = "make && EXTRA_CLING_ARGS=-I$(pwd)/../../CPyCppyy/include pytest -p pytest_isolate -p xdist --isolate --isolate-timeout=60 -n$(nproc || sysctl -n hw.ncpu)"
cwd = "upstream/cppyy/test"

[feature.cppyy-dev.tasks.install-cppyy-from-pypi]
cmd = "pip install --no-deps --no-build-isolation -v --force-reinstall cppyy==3.1.2"

[feature.cppyy-dev.tasks.install-cppyy-from-patched]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "patched/cppyy"

[feature.cppyy-dev.tasks.install-cppyy-from-upstream]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "upstream/cppyy"

[feature.cppyy-dev.tasks.install-flatsurf-suite]
depends-on = ["install-flatsurf-suite-dependencies", "install-gmpxxyy", "install-cppyythonizations", "install-e-antic", "install-exact-real", "install-intervalxt", "install-flatsurf", "install-sage-flatsurf"]

[feature.cppyy-dev.tasks.install-flatsurf-suite-dependencies]
cmd = "mamba install -y autoconf automake benchmark boost-cpp fmt gmpxxll hatchling ipywidgets libtool make matplotlib-base more-itertools parallel ppl ruamel.yaml sagelib surface-dynamics && pip install bidict realalg"

[feature.cppyy-dev.tasks.test-cppyythonizations]
depends-on = ["_precompiled-headers"]
cmd = "pytest -p pytest_isolate -p xdist --isolate --doctest-modules -n$(nproc || sysctl -n hw.ncpu)"
cwd = "downstream/cppyythonizations"

[feature.cppyy-dev.tasks.install-cppyythonizations]
cmd = "pip install ."
cwd = "downstream/cppyythonizations"

[feature.cppyy-dev.tasks.build-gmpxxyy]
cmd = "./bootstrap && ./configure --prefix=$CONDA_PREFIX && make"
cwd = "downstream/gmpxxyy"

[feature.cppyy-dev.tasks.install-gmpxxyy]
depends-on = ["build-gmpxxyy"]
cmd = "make install"
cwd = "downstream/gmpxxyy"

[feature.cppyy-dev.tasks.test-gmpxxyy]
depends-on = ["_precompiled-headers", "build-gmpxxyy"]
cmd = "make check"
cwd = "downstream/gmpxxyy"

[feature.cppyy-dev.tasks.build-e-antic]
cmd = './bootstrap && CC="ccache $CC" CXX="ccache $CXX" ./configure --without-doc --prefix=$CONDA_PREFIX && make V=1'
cwd = "downstream/e-antic"

[feature.cppyy-dev.tasks.install-e-antic]
depends-on = ["build-e-antic"]
cmd = "make install"
cwd = "downstream/e-antic"

[feature.cppyy-dev.tasks.test-e-antic]
depends-on = ["_precompiled-headers", "build-e-antic"]
cmd = "make check"
cwd = "downstream/e-antic"

[feature.cppyy-dev.tasks.build-exact-real]
cmd = './bootstrap && CC="ccache $CC" CXX="ccache $CXX" ./configure --without-doc --prefix=$CONDA_PREFIX && make V=1'
cwd = "downstream/exact-real"

[feature.cppyy-dev.tasks.install-exact-real]
depends-on = ["build-exact-real"]
cmd = "make install"
cwd = "downstream/exact-real"

[feature.cppyy-dev.tasks.test-exact-real]
depends-on = ["_precompiled-headers", "build-exact-real"]
cmd = "make check"
cwd = "downstream/exact-real"

[feature.cppyy-dev.tasks.build-intervalxt]
cmd = './bootstrap && CC="ccache $CC" CXX="ccache $CXX" ./configure --without-doc --prefix=$CONDA_PREFIX && make V=1'
cwd = "downstream/intervalxt"

[feature.cppyy-dev.target.osx.tasks.build-intervalxt]
# re-enable mem_fun_ref in macOS when building with C++17 (used by dependency PPL.)
cmd = './bootstrap && CC="ccache $CC" CXX="ccache $CXX" CXXFLAGS="$CXXFLAGS -D_LIBCPP_ENABLE_CXX17_REMOVED_BINDERS" ./configure --without-doc --prefix=$CONDA_PREFIX && make V=1'
cwd = "downstream/intervalxt"

[feature.cppyy-dev.tasks.install-intervalxt]
depends-on = ["build-intervalxt"]
cmd = "make install"
cwd = "downstream/intervalxt"

[feature.cppyy-dev.tasks.test-intervalxt]
depends-on = ["_precompiled-headers", "build-intervalxt"]
cmd = "make check"
cwd = "downstream/intervalxt"

[feature.cppyy-dev.tasks.build-flatsurf]
cmd = './bootstrap && CC="ccache $CC" CXX="ccache $CXX" ./configure --without-doc --prefix=$CONDA_PREFIX && make V=1'
cwd = "downstream/flatsurf"

[feature.cppyy-dev.tasks.install-flatsurf]
depends-on = ["build-flatsurf"]
cmd = "make install"
cwd = "downstream/flatsurf"

[feature.cppyy-dev.tasks.test-flatsurf]
depends-on = ["_precompiled-headers", "build-flatsurf"]
cmd = "make check"
cwd = "downstream/flatsurf"

[feature.cppyy-dev.tasks.install-sage-flatsurf]
cmd = "pip install --no-deps --no-build-isolation -e ."
cwd = "downstream/sage-flatsurf"

[feature.cppyy-dev.tasks.test-sage-flatsurf]
depends-on = ["_precompiled-headers", "install-sage-flatsurf"]
cmd = "sage -tp --long --optional=sage,gmpxxyy,pyeantic,pyexactreal,pyflatsurf flatsurf && pytest test"
cwd = "downstream/sage-flatsurf"

[feature.dev-builtin-llvm.tasks.install]
depends-on = ["configure-cppyy-cling-patched-builtin-llvm", "build-cppyy-cling-patched", "install-cppyy-cling-patched", "install-cppyy-backend-from-patched", "install-cpycppyy-from-patched", "install-cppyy-from-patched"]

[feature.dev-conda-forge-llvm.tasks.install]
depends-on = ["configure-cppyy-cling-patched-conda-forge-llvm", "build-cppyy-cling-patched", "install-cppyy-cling-patched", "install-cppyy-backend-from-patched", "install-cpycppyy-from-patched", "install-cppyy-from-patched"]

[feature.cppyy-dev-conda-forge.tasks.install]
depends-on = ["install-cppyy-from-patched"]

[feature.cppyy-dev-pypi.tasks.install]
depends-on = ["install-cppyy-from-patched"]

##############
# ACTIVATION #
##############
[activation.env]
MAKEFLAGS = "-j$(nproc || sysctl -n hw.ncpu)"
CMAKE_C_COMPILER_LAUNCHER = "ccache"
CMAKE_CXX_COMPILER_LAUNCHER = "ccache"
# builtin_cling: We want to build cling. That's why we're here.
# runtime_cxxmodules: (whatever that might be) leads to "error: unknown argument: '-fmodule-name'" during the build; also disabled by upstream's setup.py
# CMAKE_CXX_STANDARD: clang at least is using some C++17 features
# CMAKE_BUILD_TYPE: enable debug symbols but build release like upstream does
# LLVM_ENABLE_ASSERTIONS: work around assertion errors; upstream does the same
# LLVM_ENABLE_TERMINFO: we do not build a REPL Cling; upstream does the same
CMAKE_ARGS_CPPYY_CLING = "-Dbuiltin_cling=ON -Druntime_cxxmodules=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ENABLE_ASSERTIONS=OFF -DLLVM_ENABLE_TERMINFO=OFF"
# pytest-isolate breaks some tests due to: https://github.com/gilfree/pytest-isolate/issues/12 so we want to specify the plugins we want explicitly instead
PYTEST_DISABLE_PLUGIN_AUTOLOAD = "1"

[feature.cppyy-cling-dev.target.osx.activation.env]
# cling uses path, see https://conda-forge.org/docs/maintainer/knowledge_base/#newer-c-features-with-old-sdk
CXXFLAGS = "${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
