[workspace]
channels = ["conda-forge"]
name = "cppyy"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "6.30.0"

[environments]
feedstock-dev = ["feedstock-dev"]
# TODO: Make these environments available, see README.md
# cppyy-cling-dev-builtin-llvm = [?]
# cppyy-cling-dev-conda-forge-llvm = [?]
# cppyy-cling-dev-local-builtin-llvm = [?]
# cppyy-cling-dev-local-conda-forge-llvm = [?]
# cppyy-backend-dev-local-builtin-llvm = [?]
# cppyy-backend-dev-local-conda-forge-llvm = [?]
# cppyy-backend-dev-conda-forge = [?]
# cppyy-backend-dev-pypi = [?]
# cpycppyy-dev-local-builtin-llvm = [?]
# cpycppyy-dev-local-conda-forge-llvm = [?]
# cpycppyy-dev-conda-forge = [?]
# cpycppyy-dev-pypi = [?]
# cppyy-dev-local-builtin-llvm = [?]
# cppyy-dev-local-conda-forge-llvm = [?]
cppyy-dev-conda-forge = ["cppyy-dev", "cppyy-dev-conda-forge"]
cppyy-dev-pypi = ["cppyy-dev", "cppyy-dev-pypi"]
cppyy-pypi = ["cppyy-dev", "cppyy-pypi"]
cppyy-conda-forge = ["cppyy-dev", "cppyy-conda-forge"]

################
# DEPENDENCIES #
################
[dependencies]
pip = "*"
setuptools = "*"

[feature.feedstock-dev.dependencies]
conda-build = "*"
conda-smithy = "*"
conda-recipe-manager = "*"

[feature.cppyy-cling-dev.dependencies]
python = "*"
cxx-compiler = "*"
sed = "*"
cmake = "*"
findutils = "*"
make = "*"
libboost-headers = "*"
pip = "*"
setuptools = "*"
zlib = "*"

[feature.conda-forge-llvm.dependencies]
clangdev = { version="13.*", build="root_63004*" }

[feature.cppyy-backend-dev.dependencies]
python = "*"
cxx-compiler = "*"
pip = "*"
setuptools = "*"

[feature.conda-forge-cppyy-cling.dependencies]
cppyy-cling = "==6.30.0"

[feature.cppyy-dev.dependencies]
pytest = "*"
make = "*"

[feature.cppyy-dev-conda-forge.dependencies]
cppyy-cling = "==6.30.0"
cppyy-backend = "==1.15.2"
cpycppyy = "==1.12.16"

[feature.cppyy-dev-pypi.dependencies]
cxx-compiler = "*"

[feature.cppyy-dev-pypi.pypi-dependencies]
cppyy-cling = "==6.30.0"
cppyy-backend = "==1.15.2"
CpyCppyy = "==1.12.16"

[feature.cppyy-pypi.dependencies]
cxx-compiler = "*"

[feature.cppyy-pypi.target.linux-64.dependencies]
# Clang 13 which cppyy 3.1.2 is based upon cannot parse GCC 12 headers, see https://github.com/wlav/cppyy/issues/285
gcc = "11.*"

[feature.cppyy-pypi.pypi-dependencies]
cppyy = "==3.1.2"

[feature.cppyy-conda-forge.dependencies]
cppyy = "==3.1.2"

#########
# TASKS #
#########
[feature.cppyy-dev.tasks.test]
# TODO: Tests do not pass:
# In cppyy-pypi, we get stltypes.cxx:18:59: error: 'operator!=' is not a template function
# In cppyy-conda-forge (and all other setups) we get a segfault.
# I should report this upstream and find out how to make this pass.
cmd = "make clean && make && make test"
cwd = "upstream/cppyy/test"

[feature.cppyy-dev.tasks.install-cppyy-from-pypi]
cmd = "pip install --no-deps --no-build-isolation -v --force-reinstall cppyy==3.1.2"

[feature.cppyy-dev.tasks.install-cppyy-from-patched]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "patched/cppyy"

[feature.cppyy-dev.tasks.install-cppyy-from-upstream]
cmd = "pip install --no-deps --no-build-isolation -vv ."
cwd = "upstream/cppyy"

[feature.cppyy-dev-conda-forge.tasks.install]
depends-on = ["install-cppyy-from-patched"]

##############
# ACTIVATION #
##############
[activation.env]
MAKEFLAGS = "-j$(nproc || sysctl -n hw.ncpu)"
