name: Test
on: push

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cppyy-cling:
    runs-on: "${{ matrix.on }}"
    strategy:
      fail-fast: false
      matrix:
        environment: ["cppyy-cling-dev-builtin-llvm", "cppyy-cling-dev-conda-forge-llvm"]
        task: ["install-cppyy-cling-from-patched", "install-cppyy-cling-from-upstream"]
        on: ["ubuntu-24.04", "macos-15", "macos-15-intel"]
        exclude:
        # We cannot build an unpatched cppyy-cling against our clang due to the misordering of static clang dependencies when linking
        - environment: cppyy-cling-dev-conda-forge-llvm
          task: install-cppyy-cling-from-upstream
        # We cannot build an unpatched cppyy-cling on macos due to RTTI being incorrect for InterpreterCallback.cpp
        - task: install-cppyy-cling-from-upstream
          on: macos-15
        # We cannot build an unpatched cppyy-cling on macos due to RTTI being incorrect for InterpreterCallback.cpp
        - task: install-cppyy-cling-from-upstream
          on: macos-15-intel
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: prefix-dev/setup-pixi@v0.9.3
      with:
        pixi-version: v0.59.0
        environments: ${{ matrix.environment }}
        activate-environment: true
    - name: Run install macOS SDK (x86_64)
      run: |
        pixi run install-osx-sdk 10.13
        echo "SDKROOT='$(dirname "${SDKROOT}")/MacOSX10.13.sdk'" >> "${GITHUB_ENV}"
      if: ${{ matrix.on == 'macos-15-intel' }}
    - name: Run install macOS SDK (arm64)
      run: |
        pixi run install-osx-sdk 11.0
        echo "SDKROOT='$(dirname "${SDKROOT}")/MacOSX11.0.sdk'" >> "${GITHUB_ENV}"
      if: ${{ matrix.on == 'macos-15' }}
    - name: Run install task
      run: VERBOSE=1 pixi run ${{ matrix.task }}
    - uses: flatsurf/actions/show-logs@main
      if: ${{ always() }}
  cppyy-backend:
    runs-on: "${{ matrix.on }}"
    strategy:
      fail-fast: false
      matrix:
        environment: ["cppyy-backend-dev-conda-forge", "cppyy-backend-dev-pypi"]
        task: ["install-cppyy-backend-from-patched", "install-cppyy-backend-from-upstream"]
        on: ["ubuntu-24.04", "macos-15", "macos-15-intel"]
        exclude:
          # Until a new cppyy-cling has been released on conda-forge, we cannot build against it here.
          - environment: "cppyy-backend-dev-conda-forge"
          # Installing cppyy-cling from PyPI fails on Silicon, see https://github.com/wlav/cppyy/issues/326
          - environment: "cppyy-backend-dev-pypi"
            on: "macos-15"
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: prefix-dev/setup-pixi@v0.9.3
      with:
        pixi-version: v0.59.0
        environments: ${{ matrix.environment }}
        activate-environment: true
    - name: Run install task
      run: VERBOSE=1 pixi run ${{ matrix.task }}
    - uses: flatsurf/actions/show-logs@main
      if: ${{ always() }}
  cpycppyy:
    runs-on: "${{ matrix.on }}"
    strategy:
      fail-fast: false
      matrix:
        environment: ["cpycppyy-dev-conda-forge", "cpycppyy-dev-pypi"]
        task: ["install-cpycppyy-from-patched", "install-cpycppyy-from-upstream"]
        on: ["ubuntu-24.04", "macos-15", "macos-15-intel"]
        exclude:
          # Until a new cppyy-backend has been released on conda-forge, we cannot build against it here.
          - environment: "cpycppyy-dev-conda-forge"
          # Installing cppyy-cling from PyPI fails on Silicon, see https://github.com/wlav/cppyy/issues/326
          - environment: "cpycppyy-dev-pypi"
            on: "macos-15"
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: prefix-dev/setup-pixi@v0.9.3
      with:
        pixi-version: v0.59.0
        environments: ${{ matrix.environment }}
        activate-environment: true
    - name: Run install task
      run: VERBOSE=1 pixi run ${{ matrix.task }}
    - uses: flatsurf/actions/show-logs@main
      if: ${{ always() }}
  cppyy:
    runs-on: "${{ matrix.on }}"
    strategy:
      fail-fast: false
      matrix:
        environment: ["cppyy-dev-conda-forge", "cppyy-dev-pypi", "cppyy-pypi", "cppyy-conda-forge", "dev-builtin-llvm", "dev-conda-forge-llvm"]
        on: ["ubuntu-24.04", "macos-15", "macos-15-intel"]
        include:
          # - environment: cppyy-dev-conda-forge
          #   installation: install-cppyy-from-patched
          - environment: cppyy-dev-pypi
            installation: install-cppyy-from-patched
          - environment: dev-builtin-llvm
            installation: install
          - environment: dev-conda-forge-llvm
            installation: install
        exclude:
          # Until a new cpycppyy has been released on conda-forge, we cannot build against it here.
          - environment: "cppyy-dev-conda-forge"
          # Until cppyy has been released on conda-forge, we cannot test it here.
          - environment: "cppyy-conda-forge"
          # Installing cppyy-cling from PyPI fails on Silicon, see https://github.com/wlav/cppyy/issues/326
          - environment: "cppyy-pypi"
            on: "macos-15"
          # Installing cppyy-cling from PyPI fails on Silicon, see https://github.com/wlav/cppyy/issues/326
          - environment: "cppyy-pypi"
            on: "macos-15-intel"
          # Installing cppyy-cling from PyPI fails on Silicon, see https://github.com/wlav/cppyy/issues/326
          - environment: "cppyy-dev-pypi"
            on: "macos-15"
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: prefix-dev/setup-pixi@v0.9.3
      with:
        pixi-version: v0.59.0
        environments: ${{ matrix.environment }}
        activate-environment: true
    - name: Run install macOS SDK (x86_64)
      run: |
        pixi run install-osx-sdk 10.13
        echo "SDKROOT='$(dirname "${SDKROOT}")/MacOSX10.13.sdk'" >> "${GITHUB_ENV}"
      if: ${{ matrix.on == 'macos-15-intel' }}
    - name: Run install macOS SDK (arm64)
      run: |
        pixi run install-osx-sdk 11.0
        echo "SDKROOT='$(dirname "${SDKROOT}")/MacOSX11.0.sdk'" >> "${GITHUB_ENV}"
      if: ${{ matrix.on == 'macos-15' }}
    - name: Pin installed cppyy
      run: mamba list --json |  jq -r '.[] | select(.name=="cppyy") | "\(.name) ==\(.version)"' > $CONDA_PREFIX/conda-meta/pinned
      if: ${{ matrix.environment == 'cppyy-conda-forge' }}
    - name: Run install task
      run: VERBOSE=1 pixi run ${{ matrix.installation }}
      if: ${{ matrix.installation }}
    - name: Run cppyy test suite
      id: test-cppyy
      run: pixi run test
      continue-on-error: true
    - name: Prepare for downstream tests
      uses: nick-fields/retry@v3
      with:
        # Retry mamba install since sometimes we get network timeouts in CI here.
        max_attempts: 5
        timeout_minutes: 15
        retry_on: error
        command: pixi run install-flatsurf-suite-dependencies
    - name: Run cppyythonizations test suite
      id: test-cppyythonizations
      run: pixi run test-cppyythonizations
      continue-on-error: true
    - name: Install cppyythonizations for later tests
      run: pixi run install-cppyythonizations
    - name: Run gmpxxyy test suite
      id: test-gmpxxyy
      run: pixi run test-gmpxxyy
      continue-on-error: true
    - name: Install gmpxxyy for later tests
      run: pixi run install-gmpxxyy
    - name: Run e-antic test suite
      id: test-e-antic
      run: pixi run test-e-antic
      continue-on-error: true
    - name: Install e-antic for later tests
      run: pixi run install-e-antic
    - name: Run exact-real test suite
      id: test-exact-real
      run: pixi run test-exact-real
      continue-on-error: true
    - name: Install exact-real for later tests
      run: pixi run install-exact-real
    - name: Run intervalxt test suite
      id: test-intervalxt
      run: pixi run test-intervalxt
      continue-on-error: true
    - name: Install intervalxt for later tests
      run: pixi run install-intervalxt
    - name: Run flatsurf test suite
      id: test-flatsurf
      run: pixi run test-flatsurf
      continue-on-error: true
    - name: Install flatsurf for later tests
      run: pixi run install-flatsurf
    - name: Run sage-flatsurf test suite
      id: test-sage-flatsurf
      run: pixi run test-sage-flatsurf
      continue-on-error: true
    - name: Fail job if any downstream tests failed
      if: ${{ always() }}
      run: |
        failed=0

        expected_outcome() {
          label="$1"
          expected="success"
          case "$label" in
          esac
          echo "$expected"
        }

        check() {
          label="$1"
          outcome="$2"
          expected=$(expected_outcome "$label")

          if [ "$outcome" = "skipped" ]; then
            return
          elif [ "$outcome" != "$expected" ]; then
            echo "::error title=${label}::${label} ${outcome} in ${{ matrix.environment }}/${{ matrix.on }} (expected ${expected})"
            failed=1
          elif [ "$outcome" = "failure" ]; then
            echo "::warning title=${label}::${label} failed as expected in ${{ matrix.environment }}/${{ matrix.on }}"
          fi
        }

        check "cppyy test suite" "${{ steps.test-cppyy.outcome }}"
        check "cppyythonizations test suite" "${{ steps.test-cppyythonizations.outcome }}"
        check "gmpxxyy test suite" "${{ steps.test-gmpxxyy.outcome }}"
        check "e-antic test suite" "${{ steps.test-e-antic.outcome }}"
        check "exact-real test suite" "${{ steps.test-exact-real.outcome }}"
        check "intervalxt test suite" "${{ steps.test-intervalxt.outcome }}"
        check "flatsurf test suite" "${{ steps.test-flatsurf.outcome }}"
        check "sage-flatsurf test suite" "${{ steps.test-sage-flatsurf.outcome }}"

        if [ "$failed" -ne 0 ]; then
          exit 1
        fi
    - uses: flatsurf/actions/show-logs@main
      if: ${{ always() }}
